# Generated by Django 3.0.2 on 2020-11-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=125, null=True)),
                ('q_type', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.CharField(max_length=100, null=True)),
                ('participant_id', models.CharField(max_length=100, null=True)),
                ('participant_key', models.CharField(max_length=100, null=True)),
                ('calender_id', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'paper_instance',
            },
        ),
        migrations.CreateModel(
            name='Paper_section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_paper_id', models.IntegerField(null=True)),
                ('section_name', models.CharField(max_length=20)),
                ('section_instructions', models.CharField(max_length=400, null=True)),
                ('section_marks', models.CharField(max_length=400, null=True)),
            ],
            options={
                'db_table': 'paper_section',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('participant_email', models.CharField(max_length=100, null=True)),
                ('participant_phone', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=256)),
                ('question_type', models.CharField(max_length=20)),
                ('question_audio', models.IntegerField(blank=True, null=True)),
                ('question_video', models.IntegerField(blank=True, null=True)),
                ('question_complexity', models.IntegerField(blank=True, null=True)),
                ('question_marks', models.IntegerField(blank=True, null=True)),
                ('question_topic', models.IntegerField(blank=True, null=True)),
                ('question_subtopic', models.IntegerField(blank=True, null=True)),
                ('question_tags', models.CharField(blank=True, max_length=256, null=True)),
                ('question_status', models.CharField(blank=True, max_length=256, null=True)),
                ('q_choices', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
