# Generated by Django 3.0.2 on 2020-11-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.IntegerField()),
                ('participant_instance_id', models.IntegerField()),
                ('schedule_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'calender',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('company_add1', models.CharField(blank=True, max_length=100, null=True)),
                ('company_add2', models.CharField(blank=True, max_length=100, null=True)),
                ('company_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_state', models.CharField(blank=True, max_length=100, null=True)),
                ('company_country', models.CharField(blank=True, max_length=100, null=True)),
                ('company_domain', models.CharField(blank=True, max_length=4, null=True)),
                ('company_status', models.CharField(blank=True, max_length=1, null=True)),
                ('company_organization', models.IntegerField()),
                ('company_website', models.CharField(blank=True, max_length=100, null=True)),
                ('company_phone1', models.CharField(blank=True, max_length=100, null=True)),
                ('company_phone2', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_code', models.CharField(max_length=3)),
                ('domain_name', models.CharField(max_length=100)),
                ('domain_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(max_length=1)),
                ('mediaorigin', models.CharField(blank=True, max_length=1, null=True)),
                ('media_url', models.CharField(blank=True, max_length=256, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
                ('updatedby', models.IntegerField(blank=True, null=True)),
                ('dateofcreation', models.DateTimeField(blank=True, null=True)),
                ('dateofupdation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('option_name', models.CharField(max_length=100, null=True)),
                ('option_order', models.IntegerField(blank=True, null=True)),
                ('option_answer', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.IntegerField(blank=True, null=True)),
                ('paper_name', models.CharField(max_length=100, null=True)),
                ('paper_marks', models.IntegerField()),
                ('paper_instructions', models.CharField(max_length=256, null=True)),
                ('paper_subject', models.IntegerField()),
                ('paper_level', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'paper',
            },
        ),
        migrations.CreateModel(
            name='Paper_answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_date', models.DateTimeField(null=True)),
                ('answer_paper_id', models.IntegerField()),
                ('answer_paper_instance_id', models.IntegerField()),
                ('answer_subject_id', models.IntegerField()),
                ('answer_question_id', models.IntegerField()),
                ('answer_participant_id', models.IntegerField()),
                ('answer_question_response', models.CharField(blank=True, max_length=256, null=True)),
                ('answer_correct', models.CharField(blank=True, max_length=1, null=True)),
                ('aswer_time_given', models.IntegerField(blank=True, null=True)),
                ('asnwer_time_used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper_answer',
            },
        ),
        migrations.CreateModel(
            name='Paper_Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.IntegerField(blank=True, null=True)),
                ('question_id', models.IntegerField(blank=True, null=True)),
                ('section_id', models.IntegerField(blank=True, null=True)),
                ('question_order', models.IntegerField(blank=True, null=True)),
                ('question_type', models.CharField(blank=True, max_length=1, null=True)),
                ('question_level', models.IntegerField(blank=True, null=True)),
                ('question_marks', models.IntegerField(blank=True, null=True)),
                ('question_topic', models.IntegerField(blank=True, null=True)),
                ('question_subtopic', models.IntegerField(blank=True, null=True)),
                ('question_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paper_question',
            },
        ),
        migrations.CreateModel(
            name='Paper_results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_id', models.IntegerField()),
                ('participant_id', models.IntegerField()),
                ('calender_id', models.IntegerField()),
                ('participant_key', models.CharField(max_length=16)),
                ('paper_instance_date', models.DateTimeField()),
                ('paper_participate_result', models.CharField(blank=True, max_length=1, null=True)),
                ('paper_participate_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('paper_result_status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'paper_results',
            },
        ),
        migrations.CreateModel(
            name='Sub_topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtopic_name', models.CharField(max_length=100)),
                ('subtopic_status', models.CharField(max_length=1)),
                ('subtopic_topic', models.IntegerField()),
            ],
            options={
                'db_table': 'subtopic',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_status', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_status', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateofupdation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_choices',
        ),
        migrations.AddField(
            model_name='paper_instance',
            name='paper_instance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='company_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='participate_add1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='participate_add2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='registration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='createdby',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='dateofcreation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='dateofupdation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_lastused',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='updatedby',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper_instance',
            name='calender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper_instance',
            name='paper_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper_instance',
            name='participant_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper_instance',
            name='participant_key',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper_section',
            name='section_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paper_section',
            name='section_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=1),
        ),
    ]
